api_url = "https://huggingface.co/api/datasets"
limit = 100
hf_token = ""
dataset_large_cutoff = 10485760 # 10 MB in bytes
# large_dataset_names = []
large_dataset_names = ["RIPS-Goog-23/IIT-CDIP"]
checkout_directory = "~/hf/downloaded_datasets"
xet_clone_repo_directory = "~/hf/xet_upload_datasets"
xet_clone_repo_url = ""
