[package]
name = "prometheus_dict_encoder"
version = "0.12.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus = "0.13.0"
memchr = "^2.3"
tracing = "0.1.31"

[features]
strict = []
