name: commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v2
        with:
          version: "23.1"
          repo-token: ${{ secrets.DEV_GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@1.76.0
        with:
          components: clippy
      - name: Lint (Linux only)
        if: runner.os == 'Linux'
        run: |
          cd rust
          cargo clippy -r --verbose -- -D warnings # elevates warnings to errors
      - name: Build
        shell: bash
        run: |
          cd rust
          if [ $RUNNER_OS = 'Windows' ]; then
            cargo build --verbose
          elif [ $RUNNER_OS = 'macOS' ]; then
            brew install openssl@3
            RUST_BACKTRACE=1 cargo build --verbose --no-default-features --features "strict"
          else
            RUST_BACKTRACE=1 cargo build --verbose --features "strict"
          fi
      - name: Test Environment
        shell: bash
        run: |
          if [ $RUNNER_OS = 'macOS' ]; then
            brew install md5sha1sum
          fi
          cd rust
          
          # we need a basic git configuration for the tests to pass
          git config --global user.email operations@xetdata.com
          git config --global user.name "XetData Automation"
      - name: Test
        run: |
          cd rust
          RUST_BACKTRACE=1 cargo test --no-default-features
