name: commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v2
        with:
          version: "23.1"
          repo-token: ${{ secrets.DEV_GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@1.76.0
        with:
          components: clippy
      - uses: actions/github-script@v6
        with:
          script: |
           core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
           core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '')
      - name: Install scoop (windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression  
          scoop install sccache
          $sccachePath = (Get-Command sccache).Source
          Copy-Item -Path $sccachePath -Destination ".\sccache.exe" 
      - name: Env
        run: |
          env|sort
      - name: Install sccache (non-windows)
        shell: bash
        run: |
          if [ $RUNNER_OS = 'macOS' ]; then
              brew install sccache
              cp `which sccache` ./
          elif [ $RUNNER_OS = 'Linux' ]; then
              curl -LO https://github.com/mozilla/sccache/releases/download/v0.7.7/sccache-v0.7.7-i686-unknown-linux-musl.tar.gz
              tar xf sccache-v0.7.7-i686-unknown-linux-musl.tar.gz
              cp ./*/sccache ./ 
          fi
          echo "sccache enabled with \"$RUSTC_WRAPPER\""
      - name: Lint (Linux only)
        if: runner.os == 'Linux'
        run: |
          cd rust
          cargo clippy -r --verbose -- -D warnings # elevates warnings to errors
      - name: Build
        shell: bash
        run: |
          set +x
          if [ $RUNNER_OS = 'Windows' ]; then
            export RUSTC_WRAPPER="${PWD}/sccache.exe"
          else
            export RUSTC_WRAPPER="${PWD}/sccache"
          fi

          cd rust
          if [ $RUNNER_OS = 'Windows' ]; then
            cargo build --verbose
          elif [ $RUNNER_OS = 'macOS' ]; then
            brew install openssl@3
            RUST_BACKTRACE=1 cargo build --verbose --no-default-features --features "strict"
          else
            RUST_BACKTRACE=1 cargo build --verbose --features "strict"
          fi
      - name: Test Environment
        shell: bash
        run: |
          set +x
          if [ $RUNNER_OS = 'macOS' ]; then
            brew install md5sha1sum
            brew install openssl@3
          fi
          cd rust
          
          # we need a basic git configuration for the tests to pass
          git config --global user.email operations@xetdata.com
          git config --global user.name "XetData Automation"
      - name: Test
        shell: bash
        run: |
          set +x
          if [ $RUNNER_OS = 'Windows' ]; then
            export RUSTC_WRAPPER="${PWD}/sccache.exe"
          else
            export RUSTC_WRAPPER="${PWD}/sccache"
          fi
          cd rust
          RUST_BACKTRACE=1 cargo test 
